version: '2'

services: 
    website:
        build: .
        command: >
            gunicorn -b 0.0.0.0:5000
            --access-logfile -
            --reload
            "website.app:create_app()"
        environment:
            PYTHONUNBUFFERED: 'true'
        volumes:
            - '.:/website'
        ports:
            - '5000:5000'

volumes:
    website: